version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint..."
      - pip install cfn-lint

  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint template.yaml
      - echo "CloudFormation template validation passed!"
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  name: ValidatedTemplate